# docker-compose.gateway.yml

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  sip-gateway:
    image: ghcr.io/sentiric/sentiric-sip-gateway-service:${TAG:-latest}
    container_name: sentiric-gateway-sip-gateway-1
    env_file: [".env.generated"]
    ports: ["${SIP_GATEWAY_SERVICE_PORT:-5060}:${SIP_GATEWAY_LISTEN_PORT:-5060}/udp"]
    networks: [sentiric-net]
    restart: always

  api-gateway:
    image: ghcr.io/sentiric/sentiric-api-gateway-service:${TAG:-latest}
    container_name: sentiric-gateway-api-gateway-1
    env_file: [".env.generated"]
    volumes: ["${CONFIG_REPO_PATH}/tls/certs:/etc/sentiric/tls:ro"]
    ports: ["${API_GATEWAY_SERVICE_PORT:-8080}:8080"]
    networks: [sentiric-net]
    restart: always