# docker-compose.prod.yml

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

volumes:
  # postgres_data:
  # rabbitmq_data:
  # qdrant_data:
  # redis-data:
  stt-model-cache:

services:
  # VERİ KATMANI
  # üretim ortamı neon da yer alıyor
  # postgres:
  #   image: postgres:16-alpine
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./postgres-init:/docker-entrypoint-initdb.d
  #   # ports:
  #   #   - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
  #   networks:
  #     - sentiric-net
  #   profiles:
  #     - default
  #     - data
  #   restart: always

  # üretim ortamı için cloudamqp
  # rabbitmq:
  #   image: rabbitmq:4.1.0-management-alpine
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq/
  #   # ports:
  #   #   - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
  #   #   - "15672:15672"
  #   networks:
  #     - sentiric-net
  #   profiles:
  #     - default
  #     - data
  #   restart: always

  # Üretim ortamı qdrant.io da yer alıyor
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   env_file:
  #     - ./.env.docker    
  # ports:
  #   - "${VECTOR_DB_PORT}:${VECTOR_DB_PORT}"
  #   networks:
  #     - sentiric-net
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   restart: always
  #   profiles:
  #     - default
  #     - data  
  
  # Üretim ortamı upstash da yer alıyor
  # redis:
  #   image: redis:7-alpine
  #   env_file:
  #     - ./.env.docker    
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - sentiric-net
  #   volumes:
  #     - redis-data:/data
  #   restart: always
  #   profiles:
  #     - default
  #     - data         

  # UYGULAMA SERVİSLERİ
  user-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-user-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${USER_SERVICE_GRPC_PORT}:${USER_SERVICE_GRPC_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - app
    restart: always

  agent-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-agent-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${AGENT_SERVICE_GRPC_PORT}:${AGENT_SERVICE_GRPC_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - app
    restart: always

  dialplan-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-dialplan-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${DIALPLAN_SERVICE_GRPC_PORT}:${DIALPLAN_SERVICE_GRPC_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - app
    restart: always

  api-gateway:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-api-gateway-service:${TAG:-latest}  
    env_file:
      - ./.env
    ports:
      - "${API_GATEWAY_SERVICE_PORT}:${API_GATEWAY_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - app
    restart: always
    depends_on:
      user-service:
        condition: service_started
      # Gelecekte eklenecek diğer servisler...
      # dialplan-service:
      #   condition: service_started        

  media-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-media-service:${TAG:-latest}
    env_file:
      - ./.env
    ports:
      - "${RTP_SERVICE_PORT_MIN:-10000}-${RTP_SERVICE_PORT_MAX:-10100}:${RTP_SERVICE_PORT_MIN:-10000}-${RTP_SERVICE_PORT_MAX:-10100}/udp"
      # - "${MEDIA_SERVICE_GRPC_PORT}:${MEDIA_SERVICE_GRPC_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - telekom
    restart: always

  cdr-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-cdr-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   # Metriklerin Prometheus tarafından okunabilmesi için
    #   - "${METRICS_PORT:-9092}:${METRICS_PORT:-9092}"    
    #   - "${CDR_SERVICE_PORT}:${CDR_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - app
    restart: always

  connectors-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-connectors-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${CONNECTOR_SERVICE_PORT}:${CONNECTOR_SERVICE_PORT}"

    networks:
      - sentiric-net
    profiles:
      - default
      - app
    restart: always   

  dashboard-ui:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-connectors-service:${TAG:-latest}

    env_file:
      - ./.env

    # ports:
    #   - "${DASHBOARD_UI_PORT}:80"
    networks:
      - sentiric-net
    profiles:
      - default
      - ui
    restart: always          

  web-agent-ui:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-web-agent-ui:${TAG:-latest}

    env_file:
      - ./.env

    # ports:
    #   - "${WEB_AGENT_UI_PORT}:80"
    networks:
      - sentiric-net
    profiles:
      - default
      - ui
    restart: always  

  knowledge-service:
    
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-knowledge-service:${TAG:-latest}

    env_file:
      - ./.env
    
    # YENİ: Yerel 'data' klasörünü container içindeki '/app/data' klasörüne bağlıyoruz.
    volumes:
      - ./data:/app/data

    # ports:
    #   - "${KNOWLEDGE_SERVICE_PORT}:${KNOWLEDGE_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - ai
    restart: always          

  # AĞ GEÇİTLERİ
  sip-signaling:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-sip-signaling-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${SIP_SIGNALING_SERVICE_PORT}:${SIP_SIGNALING_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - telekom
    restart: always

  sip-gateway:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-sip-gateway-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${SIP_GATEWAY_SERVICE_PORT}:5060/udp"
    networks:
      - sentiric-net
    profiles:
      - default
      - telekom
    restart: always

  # AI SERVİSLERİ
  llm-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-llm-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${LLM_SERVICE_PORT}:${LLM_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - ai
    restart: always

  tts-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-tts-service:${TAG:-latest}
    env_file:
      - ./.env
    # ports:
    #   - "${TTS_SERVICE_PORT}:${TTS_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
      - ai
    restart: always    

  stt-service:       

      image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-stt-service:${TAG:-latest} 

      env_file: 
        - ./.env

      volumes:
        # YENİ: Model cache'ini host makineye bağlıyoruz
        - stt-model-cache:/root/.cache      
        # mTLS aktif edildiğinde bu satırları açacağız
        # - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro

      # ports:
      #   - "${STT_SERVICE_PORT}:${STT_SERVICE_PORT}"

      networks:
        - sentiric-net
      
      profiles:
        - default
        - ai

      restart: always

  task-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-task-service:${TAG:-latest} 
    env_file:
      - ./.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5003"]
    ports:
      - "${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}"
    networks:
      - sentiric-net

    restart: unless-stopped

    # depends_on:
    #   - rabbitmq
    #   - redis    

  task-service-worker:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-task-service:${TAG:-latest} 
    env_file:
      - ./.env
    
    user: "1000:1000"

    command: ["celery", "-A", "app.core.celery_app", "worker", "-l", "info"]
    
    networks:
      - sentiric-net
    
    restart: unless-stopped

    # depends_on:
    #       - rabbitmq
    #       - redis
        
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=${RABBITMQ_URL}
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    networks:
      - sentiric-net

    restart: unless-stopped

    depends_on:
      - rabbitmq    