
services:
  postgres:
    mem_limit: 256m
    cpus: 0.3

  rabbitmq:
    mem_limit: 256m
    cpus: 0.3

  user-service:
    mem_limit: 128m
    cpus: 0.2

  dialplan-service:
    mem_limit: 128m
    cpus: 0.2

  agent-service:
    mem_limit: 128m
    cpus: 0.2

  media-service:
    mem_limit: 256m
    cpus: 0.3

  sip-gateway:
    mem_limit: 128m
    cpus: 0.2

  sip-signaling:
    mem_limit: 128m
    cpus: 0.2
