# docker-compose.core.yml
networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  qdrant_data:
  redis_data:
  stt-model-cache:
  whatsapp_session:

services:
  # --- VERİ KATMANI ---
  postgres:
    image: postgres:16-alpine
    container_name: sentiric-core-postgres-1
    env_file: [".env.generated"]
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${CONFIG_REPO_PATH}/postgres-init:/docker-entrypoint-initdb.d
    networks: [sentiric-net]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: sentiric-core-rabbitmq-1
    env_file: [".env.generated"]
    ports: ["15672:15672"]
    volumes: [rabbitmq_data:/var/lib/rabbitmq/]
    networks: [sentiric-net]
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: sentiric-core-redis-1
    volumes: [redis_data:/data]
    networks: [sentiric-net]
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: sentiric-core-qdrant-1
    ports: ["${VECTOR_DB_PORT:-6333}:6333"]
    volumes: [qdrant_data:/qdrant/storage]
    networks: [sentiric-net]
    restart: always

  flower:
    image: mher/flower
    container_name: sentiric-core-flower-1
    env_file: [".env.generated"]
    ports: ["${FLOWER_PORT:-5555}:5555"]
    networks: [sentiric-net]
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      task-service-worker:
        condition: service_started
  # --- UYGULAMA SERVİSLERİ (İMAJDAN) ---
  user-service:
    image: ghcr.io/sentiric/sentiric-user-service:${TAG:-latest}
    container_name: sentiric-core-user-service-1
    env_file: [".env.generated"]
    volumes: ["../sentiric-config/tls/certs:/etc/sentiric/tls:ro"]
    networks: [sentiric-net]
    restart: always
    depends_on: { postgres: { condition: service_healthy } }

  dialplan-service:
    image: ghcr.io/sentiric/sentiric-dialplan-service:${TAG:-latest}
    container_name: sentiric-core-dialplan-service-1
    env_file: [".env.generated"]
    volumes: ["../sentiric-config/tls/certs:/etc/sentiric/tls:ro"]
    networks: [sentiric-net]
    restart: always
    depends_on: { postgres: { condition: service_healthy } }

  agent-service:
    image: ghcr.io/sentiric/sentiric-agent-service:${TAG:-latest}
    container_name: sentiric-core-agent-service-1
    env_file: [".env.generated"]
    volumes: ["../sentiric-config/tls/certs:/etc/sentiric/tls:ro"]
    ports: ["${METRICS_PORT_AGENT:-9091}:9091"]
    networks: [sentiric-net]
    restart: always
    depends_on: { postgres: { condition: service_healthy }, rabbitmq: { condition: service_healthy } }
    
  cdr-service:
    image: ghcr.io/sentiric/sentiric-cdr-service:${TAG:-latest}
    container_name: sentiric-core-cdr-service-1
    env_file: [".env.generated"]
    volumes: ["../sentiric-config/tls/certs:/etc/sentiric/tls:ro"]
    ports: ["${CDR_SERVICE_PORT:-5004}:5004", "${METRICS_PORT_CDR:-9092}:9092"]
    networks: [sentiric-net]
    restart: always
    depends_on: { postgres: { condition: service_healthy }, rabbitmq: { condition: service_healthy } }

  media-service:
    image: ghcr.io/sentiric/sentiric-media-service:${TAG:-latest}
    container_name: sentiric-core-media-service-1
    env_file: [".env.generated"]
    volumes: ["../sentiric-config/tls/certs:/etc/sentiric/tls:ro"]
    ports: ["${RTP_SERVICE_PORT_MIN}-${RTP_SERVICE_PORT_MAX}:${RTP_SERVICE_PORT_MIN}-${RTP_SERVICE_PORT_MAX}/udp"]
    networks: [sentiric-net]
    restart: always
    depends_on: [user-service, dialplan-service]

  sip-signaling:
    image: ghcr.io/sentiric/sentiric-sip-signaling-service:${TAG:-latest}
    container_name: sentiric-core-sip-signaling-1
    env_file: [".env.generated"]
    ports:
      - "${SIP_SIGNALING_SERVICE_PORT:-5060}:${SIP_SIGNALING_SERVICE_PORT:-5060}/udp"    
    volumes: ["../sentiric-config/tls/certs:/etc/sentiric/tls:ro"]
    networks: [sentiric-net]
    restart: always
    depends_on: { rabbitmq: { condition: service_healthy }, media-service: { condition: service_started } }

  connectors-service:
    image: ghcr.io/sentiric/sentiric-connectors-service:${TAG:-latest}
    container_name: sentiric-core-connectors-service-1
    env_file: [".env.generated"]
    ports: ["${CONNECTOR_SERVICE_PORT:-5005}:5005"]
    networks: [sentiric-net]
    restart: always
    depends_on: { postgres: { condition: service_healthy } }

  task-service:
    image: ghcr.io/sentiric/sentiric-task-service:${TAG:-latest}
    container_name: sentiric-core-task-service-api-1
    env_file: [".env.generated"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5003"]
    ports: ["${TASK_SERVICE_PORT:-5003}:5003"]
    networks: [sentiric-net]
    restart: always
    depends_on: { rabbitmq: { condition: service_healthy }, redis: { condition: service_healthy } }

  task-service-worker:
    image: ghcr.io/sentiric/sentiric-task-service:${TAG:-latest}
    container_name: sentiric-core-task-service-worker-1
    env_file: [".env.generated"]
    user: "sentiric_user"
    command: ["celery", "-A", "app.core.celery_app", "worker", "-l", "info"]
    networks: [sentiric-net]
    restart: always
    depends_on: { rabbitmq: { condition: service_healthy }, redis: { condition: service_healthy } }

  llm-service:
    image: ghcr.io/sentiric/sentiric-llm-service:${TAG:-latest}
    container_name: sentiric-core-llm-service-1
    env_file: [".env.generated"]
    ports: ["${LLM_SERVICE_PORT:-7860}:7860"]
    networks: [sentiric-net]
    restart: always
    depends_on: [agent-service]

  stt-service:
    image: ghcr.io/sentiric/sentiric-stt-service:${TAG:-latest}
    container_name: sentiric-core-stt-service-1
    env_file: [".env.generated"]
    volumes: [stt-model-cache:/root/.cache]
    ports: ["${STT_SERVICE_PORT:-5001}:5001"]
    networks: [sentiric-net]
    restart: always
    healthcheck: { test: ["CMD", "curl", "-f", "http://localhost:5001/health"], interval: 30s, timeout: 10s, retries: 3, start_period: 120s }

  knowledge-service:
    image: ghcr.io/sentiric/sentiric-knowledge-service:${TAG:-latest}
    container_name: sentiric-core-knowledge-service-1
    env_file: [".env.generated"]
    ports: ["${KNOWLEDGE_SERVICE_PORT:-50055}:50055"]
    volumes: ["./data:/app/data"]
    networks: [sentiric-net]
    restart: always
    depends_on: { postgres: { condition: service_healthy }, qdrant: { condition: service_started } }

  messaging-gateway:
    image: ghcr.io/sentiric/sentiric-messaging-gateway-service:${TAG:-latest}
    container_name: sentiric-core-messaging-gateway-1
    env_file: [".env.generated"]
    volumes: [whatsapp_session:/app/wweb_auth]
    networks: [sentiric-net]
    restart: always
    depends_on: { rabbitmq: { condition: service_healthy } }

  dashboard-ui:
    image: ghcr.io/sentiric/sentiric-dashboard-ui:${TAG:-latest}
    container_name: sentiric-core-dashboard-ui-1
    env_file: [".env.generated"]
    ports: ["${DASHBOARD_UI_PORT:-3000}:80"]
    networks: [sentiric-net]
    restart: always
    
  web-agent-ui:
    image: ghcr.io/sentiric/sentiric-web-agent-ui:${TAG:-latest}
    container_name: sentiric-core-web-agent-ui-1
    env_file: [".env.generated"]
    ports: ["${WEB_AGENT_UI_PORT:-3001}:80"]
    networks: [sentiric-net]
    restart: always