# Temel altyapı servislerinin tanımları
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sentiric_postgres
    env_file: .env
    volumes: ["postgres_data:/var/lib/postgresql/data"]
    networks: ["sentiric-net"]
    ports: ["5432:5432"]
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: sentiric_redis
    volumes: ["redis_data:/data"]
    networks: ["sentiric-net"]
    ports: ["6379:6379"]
    restart: unless-stopped
    
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: sentiric_rabbitmq
    env_file: .env
    volumes: ["rabbitmq_data:/var/lib/rabbitmq/"]
    networks: ["sentiric-net"]
    ports: ["5672:5672", "15672:15672"]
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: