#!/bin/bash
set -e

# Bu script, Docker Compose için son .env dosyasını oluşturur.
# Tüm karmaşık yol hesaplamalarını terk edip, dosyaları manuel olarak birleştirir.
# Bu, WSL dahil tüm ortamlarda hatasız çalışmayı garanti eder.

PROFILE=${1:-dev}

# --- Temel Dizinleri Tanımla ---
# Script'in bulunduğu dizinden yola çıkarak ana dizinleri buluyoruz.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
INFRA_DIR=$(dirname "$SCRIPT_DIR")
WORKSPACE_DIR=$(dirname "$INFRA_DIR")

# --- Kaynak ve Hedef Dosyaları Tanımla ---
CONFIG_DIR="${WORKSPACE_DIR}/sentiric-config/environments"
OUTPUT_FILE="${INFRA_DIR}/.env.generated"
PROFILE_FILE="${CONFIG_DIR}/profiles/${PROFILE}.env"

if [ ! -f "$PROFILE_FILE" ]; then
    echo "❌ HATA: Profil dosyası bulunamadı: $PROFILE_FILE"
    exit 1
fi

echo "🔧 Yapılandırma dosyası '${OUTPUT_FILE}' oluşturuluyor (Profil: ${PROFILE})..."

# --- Çıktı Dosyasını Başlat ---
{
    echo "# Auto-generated by Sentiric Orchestrator for profile: ${PROFILE}"
    echo "# DO NOT EDIT THIS FILE MANUALLY"
    echo ""
} > "$OUTPUT_FILE"

# --- Dosyaları Manuel Olarak Birleştir ---
# Profil dosyasını satır satır oku
while IFS= read -r line || [[ -n "$line" ]]; do
    # Satır "source" ile başlıyorsa
    if [[ $line == source* ]]; then
        # `source common/platform.env` gibi bir satırdan dosya yolunu al
        relative_path=$(echo "$line" | cut -d' ' -f2)
        # Yolu, ana config dizinine göre birleştir
        source_file="${CONFIG_DIR}/${relative_path}"

        if [ -f "$source_file" ]; then
            # Dosyanın içeriğini çıktıya ekle
            echo "# Included from: ${relative_path}" >> "$OUTPUT_FILE"
            grep -vE '^\s*#|^\s*$' "$source_file" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
        else
            echo "⚠️ UYARI: Kaynak dosyası bulunamadı, atlanıyor: $source_file"
        fi
    fi
done < "$PROFILE_FILE"

# --- Sırları ve Dinamik Değişkenleri Ekle ---
SECRETS_FILE="${CONFIG_DIR}/common/secrets.env"
if [ -f "$SECRETS_FILE" ]; then
    echo "# Included from: common/secrets.env" >> "$OUTPUT_FILE"
    grep -vE '^\s*#|^\s*$' "$SECRETS_FILE" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

echo "# Dynamically added by Orchestrator" >> "$OUTPUT_FILE"
DETECTED_IP=$(hostname -I | awk '{print $1}')
echo "PUBLIC_IP=${DETECTED_IP}" >> "$OUTPUT_FILE"
TAG=${TAG:-latest}
echo "TAG=${TAG}" >> "$OUTPUT_FILE"
echo "CONFIG_REPO_PATH=../sentiric-config" >> "$OUTPUT_FILE"

# Windows satır sonlarını temizle
sed -i 's/\r$//' "$OUTPUT_FILE"

echo "✅ Yapılandırma başarıyla oluşturuldu."