#!/bin/bash
set -e

# Bu script, Docker Compose için son .env dosyasını oluşturur.
# Kendi konumunu bularak, `source` komutlarındaki göreceli yolları
# güvenilir bir şekilde mutlak yollara çevirir ve doğru dosyaları birleştirir.

PROFILE=${1:-dev}

# --- KENDİ KONUMUNU BULMA ---
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
INFRA_DIR=$(dirname "$SCRIPT_DIR")
WORKSPACE_DIR=$(dirname "$INFRA_DIR")

# --- DOSYA YOLLARINI TANIMLAMA ---
CONFIG_BASE_DIR="${WORKSPACE_DIR}/sentiric-config/environments"
OUTPUT_FILE="${INFRA_DIR}/.env.generated"
SECRETS_FILE="${CONFIG_BASE_DIR}/common/secrets.env"
PROFILE_FILE="${CONFIG_BASE_DIR}/profiles/${PROFILE}.env"

if [ ! -f "$PROFILE_FILE" ]; then
    echo "❌ HATA: Profil dosyası bulunamadı: $PROFILE_FILE"
    exit 1
fi

echo "🔧 Yapılandırma dosyası '${OUTPUT_FILE}' oluşturuluyor (Profil: ${PROFILE})..."

# --- ÇIKTI DOSYASINI HAZIRLAMA ---
> "$OUTPUT_FILE"
echo "# Auto-generated by Sentiric Orchestrator for profile: ${PROFILE}" >> "$OUTPUT_FILE"
echo "# DO NOT EDIT THIS FILE MANUALLY" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# --- KAYNAK DOSYALARINI BİRLEŞTİRME ---
# Profil dosyasındaki tüm 'source' komutlarını oku
while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ $line == source* ]]; then
        relative_path=$(echo "$line" | cut -d' ' -f2)
        
        # DÜZELTME: Profil dosyasının bulunduğu dizine göre göreceli yolu çöz
        # ve ardından bu yolu "temizleyerek" mutlak ve standart bir yola dönüştür.
        # Bu, 'profiles/../common' gibi ifadelerin doğru çalışmasını sağlar.
        unresolved_path="${CONFIG_BASE_DIR}/profiles/${relative_path}"
        source_file_path=$(realpath "$unresolved_path")
        
        if [ -f "$source_file_path" ]; then
            grep -vE '^\s*#|^\s*$' "$source_file_path" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
        else
            echo "⚠️ UYARI: Kaynak dosyası bulunamadı, atlanıyor: $unresolved_path"
        fi
    fi
done < "$PROFILE_FILE"

# Sırları ekle
if [ -f "$SECRETS_FILE" ]; then
    echo "# Included from: secrets.env" >> "$OUTPUT_FILE"
    grep -vE '^\s*#|^\s*$' "$SECRETS_FILE" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# --- DİNAMİK DEĞİŞKENLERİ EKLEME ---
echo "# Dynamically added by Orchestrator" >> "$OUTPUT_FILE"
DETECTED_IP=$(hostname -I | awk '{print $1}')
echo "PUBLIC_IP=${DETECTED_IP}" >> "$OUTPUT_FILE"
TAG=${TAG:-latest}
echo "TAG=${TAG}" >> "$OUTPUT_FILE"
echo "CONFIG_REPO_PATH=../sentiric-config" >> "$OUTPUT_FILE"

# Windows satır sonlarını temizle
if command -v dos2unix &> /dev/null; then
    dos2unix "$OUTPUT_FILE" >/dev/null 2>&1 || true
elif command -v sed &> /dev/null; then
    sed -i 's/\r$//' "$OUTPUT_FILE"
fi

echo "✅ Yapılandırma başarıyla oluşturuldu."